# "server" configuration file
# disclaimer: this file is not supposed to be versionned in a real project as a ".env" file wouldn't be.

[error_tracing]
record = false

[database]
url = "sqlite:///crm.db"
echo = false
reset = false

[database_sample]
populate = true  # populate newly created database with a sample dataset

[controller]
auth_secret_key="RCxuPWd8Z3vN4mGyHrTwkYgAzchXL6EtQSpKB7qsV5neMD92aJc5k2LhAnCVZWaFEzwsmgvbGfNTrU3jMSYdpR9X4xq6HQDu7t8y"
