# "server" configuration file
# disclaimer: this file is not supposed to be versionned in a real project as a ".env" file wouldn't be.

[error_tracing]
enabled = true
dns = "https://59ffa0946fb3cd6311053048552ef225@o4506144422494208.ingest.sentry.io/4506332104884224"

[database]
url = "sqlite:///crm.db"
echo = false
reset = false

[database_sample]
populate = true  # populate newly created database with a sample dataset

[controller]
auth_secret_key="RCxuPWd8Z3vN4mGyHrTwkYgAzchXL6EtQSpKB7qsV5neMD92aJc5k2LhAnCVZWaFEzwsmgvbGfNTrU3jMSYdpR9X4xq6HQDu7t8y"
