[error_tracing]
record = false

[database]
url = "sqlite:///sample.db"
echo = false
reset = false

[database_sample]
populate_with_sample = true  # populate newly created database with a sample dataset


